title: Coming Soon
description: We are still working on our website. Stay tuned for updates!
keywords: bootstrap, template, coming soon
author: Christian Who Codes

icons:
  favicon_ico: assets/img/favicon.ico
  apple_touch_icon: assets/img/apple-touch-icon.png

background:
  image: assets/img/bg.jpg

hero:
  title: Coming Soon!
  subtitle: We are still working on our website. Stay tuned for updates!
  newsletter_text: Subscribe now to get the latest updates!

footer:
  copyright_text: All Rights Reserved.
  credits_text: Crafted with ❤️ by <a href="https://github.com/christianwhocodes" target="_blank" rel="noopener"><em>Christian Who Codes</em></a>

contact:
  email: info@example.com
  phone: +254 706 965904

address:
  street: 00600 Ngara Rd
  city: Nairobi, Kenya

hours:
  weekdays: 9AM - 5PM
  saturday: 9AM - 1PM
  sunday: Closed

social:
  twitter: https://twitter.com/myawesome
  facebook: https://facebook.com/myawesome
  instagram: https://instagram.com/myawesome
  linkedin: https://linkedin.com/in/myawesome

countdown_date: 2025/12/3
